// Compiler observations complement the original binary's call graph. Import
// through the shared Rust reader: no second schema validator or ABI inference.
import { store } from '../store';
import { h } from '../util';
import { View } from './base';

interface Signature { returnType: string; parameterTypes: string[]; variadic?: boolean }
interface Finding {
  caller: string; callee: string; source: string;
  kind: 'argument-count' | 'void-result';
  definitionAbi: Signature; declaredCallerAbi: Signature;
  actualCallCounts: (number | bigint)[]; allResultsDiscarded: boolean; oldStyle?: boolean;
  sourceSha256?: string; originalSha256?: string;
  [key: string]: unknown;
}
interface Report {
  contracts: Finding[]; scope: string; cacheMisses: string[];
  [key: string]: unknown;
}

function signature(s: Signature): string {
  const args = [...s.parameterTypes, ...(s.variadic ? ['...'] : [])];
  return `${s.returnType} (${args.join(', ') || 'void'})`;
}

// The shared WASM serializer preserves 64-bit metadata as BigInt.
function evidence(value: unknown): string {
  return JSON.stringify(value, (_key, item: unknown) => typeof item === 'bigint' ? item.toString() : item, 2);
}

export class ContractsView extends View {
  private report?: Report;
  private filename = '';
  private caller = '';
  private callee = '';
  private sequence = 0;
  private status!: HTMLElement;
  private filters!: HTMLElement;
  private results!: HTMLElement;

  constructor() { super('contracts'); }

  protected render() {
    const input = h('input', { type: 'file', accept: '.json,application/json', style: 'display:none' });
    const load = h('button', { type: 'button', class: 'btn' }, 'Import compiler report…');
    load.addEventListener('click', () => input.click());
    input.addEventListener('change', () => {
      const file = input.files?.[0];
      input.value = '';
      if (file) void this.load(file);
    });
    this.status = h('p', { role: 'status', class: 'sub' });
    this.filters = h('div', { class: 'toolbar' });
    this.results = h('div');
    this.el.replaceChildren(h('div', { class: 'page contracts-page' },
      h('div', { class: 'card' }, h('h2', null, 'Call contracts'),
        h('p', { class: 'sub' }, 'Compare reconstructed C calls with actual compiler definitions. Load an all-caller contract report generated by your decompilation build.'),
        load, input, this.status,
        h('p', { class: 'muted' }, 'Imported observations are independent of the open binary. Their hashes and native behavior are not verified here; absence of a finding does not prove a call safe.')),
      this.filters, this.results));
    this.draw();
  }

  private async load(file: File) {
    const sequence = ++this.sequence;
    this.status.textContent = `Reading ${file.name}…`;
    try {
      if (file.size > 16 * 1024 * 1024) throw new Error('Compiler report exceeds 16 MiB.');
      const report = await store.api.call<Report>('callContractsParse', await file.text());
      if (sequence !== this.sequence) return;
      this.report = report;
      this.filename = file.name;
      this.caller = this.callee = '';
      this.draw();
    } catch (e) {
      if (sequence !== this.sequence) return;
      this.status.textContent = `Could not import ${file.name}: ${e instanceof Error ? e.message : String(e)}${this.report ? ' Previous report retained.' : ''}`;
    }
  }

  private picker(label: string, values: string[], selected: string, change: (value: string) => void) {
    const select = h('select', { class: 'field', 'aria-label': label },
      h('option', { value: '' }, `All ${label.toLowerCase()}s`),
      [...new Set(values)].sort().map(value => h('option', { value }, value)));
    select.value = selected;
    select.addEventListener('change', () => { change(select.value); this.draw(); });
    return h('label', null, label, ' ', select);
  }

  private draw() {
    const report = this.report;
    if (!report) {
      this.status.textContent = 'No compiler report imported.';
      this.filters.replaceChildren();
      this.results.replaceChildren();
      return;
    }
    const rows = report.contracts.filter(r => (!this.caller || r.caller === this.caller) && (!this.callee || r.callee === this.callee));
    this.status.textContent = `${this.filename} · ${rows.length} of ${report.contracts.length} findings · ${report.cacheMisses.length} uncached callers`;
    this.filters.replaceChildren(
      this.picker('Caller', report.contracts.map(r => r.caller), this.caller, v => this.caller = v),
      this.picker('Callee', report.contracts.map(r => r.callee), this.callee, v => this.callee = v));
    this.results.replaceChildren(
      h('p', { class: 'sub' }, `Reported scope: ${report.scope}`),
      ...rows.map(r => h('details', { class: 'card contract-finding' },
        h('summary', null, h('span', { class: 'mono' }, `${r.caller} → ${r.callee}`),
          ' · ', r.kind === 'void-result' ? 'Consumes void result' : `Supplied ${r.actualCallCounts.join('/')} args; definition takes ${r.definitionAbi.parameterTypes.length}`),
        h('dl', { class: 'facts' },
          h('dt', null, 'Source'), h('dd', { class: 'mono' }, r.source),
          h('dt', null, 'Caller declaration'), h('dd', { class: 'mono' }, signature(r.declaredCallerAbi), r.oldStyle ? ' [unspecified parameter list]' : ''),
          h('dt', null, 'Actual definition'), h('dd', { class: 'mono' }, signature(r.definitionAbi)),
          h('dt', null, 'Observed result use'), h('dd', null, r.allResultsDiscarded ? 'Every observed result discarded' : 'At least one result consumed')),
        h('details', null, h('summary', null, 'Reported evidence and metadata'), h('pre', { class: 'contract-evidence' }, evidence(r))))),
      ...(rows.length === 0 ? [h('p', { class: 'sub' }, 'No findings match these exact names.')] : []),
      ...(report.cacheMisses.length ? [h('div', { class: 'card' }, h('h3', null, 'Uncached callers'), h('p', { class: 'mono' }, report.cacheMisses.join(', ')))] : []),
      h('details', { class: 'card' }, h('summary', null, 'Report metadata'), h('pre', { class: 'contract-evidence' },
        evidence(Object.fromEntries(Object.entries(report).filter(([k]) => k !== 'contracts'))))));
  }
}
