use binviz::{evidence::sha256, workspace::Workspace};
use std::{collections::BTreeMap, path::Path};
fn fixture() -> (Workspace, BTreeMap<String, Vec<u8>>) {
    let mut w = Workspace::parse(include_bytes!("../../../tests/fixtures/lowerings/workspace.json")).unwrap();
    let mut files = w
        .evidence
        .read_artifacts(&Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/lowerings"));
    let compiler = b"test compiler identity, not executable".to_vec();
    for e in [&mut w.evidence, &mut w.compiler_facts.evidence] {
        e.artifacts.iter_mut().find(|a| a.id == "compiler").unwrap().sha256 = sha256(&compiler);
    }
    files.insert("compiler".into(), compiler);
    // Ordinary tests do not redistribute the compiler or Node executable. The
    // frozen service observations were generated by actual WASM execution.
    for r in &mut w.proof_closures {
        r.dependencies.insert("compiler".into(), sha256(&files["compiler"]));
        let raw = serde_json::to_vec(r).unwrap();
        w.evidence
            .artifacts
            .iter_mut()
            .find(|a| a.id == r.review_artifact)
            .unwrap()
            .sha256 = sha256(&raw);
        files.insert(r.review_artifact.clone(), raw);
    }
    (w, files)
}
#[test]
fn gpu_discard_and_equal_arity_service_plans_are_real_typed_lowerings() {
    let (w, files) = fixture();
    let report = w.analyze(Some(&files)).unwrap();
    for name in ["frame", "poll"] {
        let caller = report.callers.iter().find(|c| c.name == name).unwrap();
        assert_eq!(
            caller.calls[0].policies[0].state, "eligible",
            "{:?} {:?}",
            caller.calls[0].reasons, caller.calls[0].policies[0].reasons
        );
    }
    let plan = binviz::adapters::plan(&w, &files, &[]).unwrap();
    assert!(plan.refused.is_empty(), "{:?}", plan.refused);
    let source = &plan.candidates[0].source;
    assert!(source.contains("(void)selected_gpu("), "{source}");
    assert!(source.contains("return selected_vblank("), "{source}");
    assert!(!source.contains("void)arg1"));
    assert_eq!(plan.references.len(), 2);
    let mut invalid = w.clone();
    let call = invalid
        .compiler_facts
        .calls
        .iter_mut()
        .find(|c| c.callee == "legacy_draw")
        .unwrap();
    call.result_consumed = true;
    assert!(binviz::adapters::plan(&invalid, &files, &["discarded-result".into()]).is_err());
    let mut invalid = w.clone();
    invalid.compiler_facts.address_references.push(serde_json::from_value(serde_json::json!({"unit":w.compiler_facts.calls[0].unit,"caller":w.compiler_facts.calls[0].caller,"declaration":w.compiler_facts.calls[0].declaration,"span":w.compiler_facts.calls[0].span})).unwrap());
    assert!(binviz::adapters::plan(&invalid, &files, &["discarded-result".into()]).is_err());
}
